language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: localmeetups-co:xTc4oYzejXFFNHsAaYEzxIkE
  email:
    - oscar@platzi.com
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master