language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: localmeetups-co:xTc4oYzejXFFNHsAaYEzxIkE
  email:
    recipients:
      - oscar@platzi.com
      - oscar@arepa.dev
    on_success: always # default: change
    on_failure: always # default: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master